---
# Vector Install
- name: Install vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Download and install vector packages for Centos8
      become: true
      ansible.builtin.yum:
        name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
        state: present
      notify: Start Vector service
      when: ansible_facts['distribution'] == "CentOS"
