- name: Install kubernetes
  hosts: all
  become: yes

  tasks:
  - name: apt-get update && apt-get upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: yes
  
  - name: Install the necessary packages
    ansible.builtin.apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl

  - name: Download the Google Cloud public signing key
    ansible.builtin.shell: curl -fsSL https://dl.k8s.io/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

  - name: Download the Google Cloud public signing key
    ansible.builtin.shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - name: Apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install kubelet, kubeadm, kubectl and containerd,
    ansible.builtin.apt:
      pkg:
      - kubelet
      - kubeadm
      - kubectl
      - containerdapt-mark hold kubelet kubeadm kubectl
  
  - name: Enable forwarding
    ansible.builtin.shell: >
      modprobe br_netfilter
      echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
      echo "net.bridge.bridge-nf-call-iptables=1" >> /etc/sysctl.conf
      echo "net.bridge.bridge-nf-call-arptables=1" >> /etc/sysctl.conf
      echo "net.bridge.bridge-nf-call-ip6tables=1" >> /etc/sysctl.conf
      sysctl -p /etc/sysctl.conf
  