apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
spec:
  selector:
    app: multitool
  ports:  
  - port: 5555
    name: nginx
    targetPort: 80
  - port: 6666
    name: multitool-http
    targetPort: 1180
  - port: 7777
    name:  multitool-https
    targetPort: 11443