apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-cred
  namespace: myapp
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlptOXVjblU2TlVWQ1NVUndhVkEyVURFME1HZDJaSGxWU0RrPSIKCQl9Cgl9Cn0K