- name: Install Docker
  hosts: all
  tasks:
    - name: Download docker files
      shell: |
        wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.6.9-1_amd64.deb
        wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~debian-bullseye_amd64.deb
        wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce_20.10.9~3-0~debian-bullseye_amd64.deb
        wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-compose-plugin_2.6.0~debian-bullseye_amd64.deb
    - name: Install iptables
      apt:
        name: iptables
        state: build-dep
      become: yes
    - name: Install Docker
      apt:
        deb: "{{item}}"
      become: yes
      with_items:
        - /home/mfonarev/containerd.io_1.6.9-1_amd64.deb
        - /home/mfonarev/docker-ce-cli_20.10.9~3-0~debian-bullseye_amd64.deb
        - /home/mfonarev/docker-ce_20.10.9~3-0~debian-bullseye_amd64.deb
        - /home/mfonarev/docker-compose-plugin_2.6.0~debian-bullseye_amd64.deb